### ISSUE TITLE
add suport for USA

### ISSUE THREAD

**Issue by MemBoi** [fewieden/MMM-Fuel#52] opened 2020-09-29 03:11 UTC
Platform (Hardware/OS):

Node version:

MagicMirror version:

Module version:

Description of the issue:

**Comment by fewieden** [comment] 2020-09-29 15:29
@MemBoi do you know about a free public API that provides the data you are asking for?

**Comment by fewieden** [comment] 2020-09-29 15:30
Duplicate of https://github.com/fewieden/MMM-Fuel/issues/45#issuecomment-625439806

**Closed by fewieden** 2020-09-29 15:30 UTC
Labels: enhancement

**Comment by fewieden** [comment] 2022-04-23 14:27
@MemBoi I just released the new version 2.3.0 with support for USA
