### ISSUE TITLE
Does the gasBuddy sortBy option work?

### ISSUE THREAD

**Issue by dyeatman** [fewieden/MMM-Fuel#116] opened 2023-10-11 15:27 UTC
Platform (Hardware/OS):  Raspberry Pi 3A+

Node version: 18.18.0

MagicMirror² version: 2.25.0

Module version:  2.4.0

Description of the issue:
Using Gasbuddy the sortBy parameter seems to have no effect.
Does it work for GasBuddy? 
BTW, showDistance always shows zero so I turned that off, I assume that doesn't work in GasBuddy.

My MM Settings:
               {
                       module: "MMM-Fuel",
                       position: "top_left",
                       config: {
                             provider: "gasbuddy",
                             types: ["regular"],
                             sortBy: "regular",
                             zip: "73071",
                             radius: 10,
                             fade: false,
                             showDistance: false,
                             max: 10
                       }

**Comment by fewieden** [comment] 2023-10-12 07:47
@dyeatman I used your config and it is sorted by price, distance is not available for the GasBuddy provider.

![image](https://github.com/fewieden/MMM-Fuel/assets/9334168/22eaf4cd-2bf4-4972-a330-08c8791fa6bb)

**Comment by dyeatman** [comment] 2023-10-12 11:29
Curious.  None of my other modules appear to be affected and work with no apparent issues..

I flushed the logs then restarted MM and captured the logs which are attached along with a screenshot.

 

One log is with all my modules loaded and the second is with just the first basic modules loaded. 

The error messages in both cases are pretty much the same and  have some curious “index out of bounds” messages.

If I eliminate all the modules, in the error log I get the same index messages and nothing else.

 

Any thoughts?  Should I reload something?

 

Thank you for your insights,

 

dave

**Comment by fewieden** [comment] 2023-10-12 17:35
@dyeatman hmm those could be errors from Electron. Did you try to run the mirror in server-only mode and access it from the browser? https://docs.magicmirror.builders/getting-started/installation.html#server-only

Your screenshot is not visible on GitHub.

**Comment by dyeatman** [comment] 2023-10-12 18:33
I uploaded the image and linked it in the wiki.

I will trey server mode to see what happens.

 

Dave

**Comment by fewieden** [comment] 2023-11-07 06:54
@dyeatman did you have a chance to test this in server-only mode?

**Comment by dyeatman** [comment] 2023-11-07 10:07
Hi,

I still doesn’t sort.  Everything else with Fuel (and the MM) works fine.

I haven’t tried it in server only mode but I will and let you know.

 

Dave

**Comment by dathbe** [comment] 2024-03-03 19:57
I'm having the same issue with both gasbuddy and autoblog (haven't tried the others).  I can't tell what it's sorting by, but it's not price.  The arrow suggests it's trying to, but the prices are all out of order.

**Comment by bmikol** [comment] 2024-03-04 00:13
Agreed; for some odd reason gasbuddy only pulls 3 stations from my zipcode, despite having 10 as the `max` value. 

Switching to autoblog, I'm seeing `max` and `radius` config properties work as expected. While the arrow indicates it's trying to do a descending sort by Price (why?), it appears that it's doing a distance sort… oddly from furthest to nearest.

I would expect that the list to be an ascending sort by either price (lowest -> highest) or distance (nearest -> furthest) – my personal preference would be by price.

**Comment by bmikol** [comment] 2024-03-08 19:56
Thanks @dathbe! @fewieden any thoughts about this issue? Thanks!

**Comment by fewieden** [comment] 2024-03-10 10:53
@dyeatman @dathbe @bmikol can you please share the configs that you used for `gasbuddy` and `autoblog`. Ideally also some screenshots of the result. Do you see any errors related to this module in the electron console or the terminal that you run the mirror in?

The last time I tried it with the config of @dyeatman from the issue description I was not able to reproduce the issue, see result here https://github.com/fewieden/MMM-Fuel/issues/116#issuecomment-1759106305

**Comment by fewieden** [comment] 2024-03-10 11:39
My bad I already fixed the issue last year, but didn't release a new version :facepalm: https://github.com/fewieden/MMM-Fuel/issues/110

When I tried to reproduce the issue I was using the development version instead of the latest release.

I just released version 2.5.0, please update to that version and see if your problems are resolved. Don't forget to install the dependencies.

**Comment by dyeatman** [comment] 2024-03-10 13:25
That finally fixed my sorting issue…Thanks!

**Comment by bmikol** [comment] 2024-03-11 02:32
Thanks @fewieden! I also can confirm the fix works and the issue's resolved with my config. Much appreciated!

**Closed** 2024-03-12 06:09 UTC
Labels: help wanted
